language: node_js
node_js: '0.10'
script:
  - grunt travis:$TEST
before_install:
  - npm install -g grunt-cli
before_script:
  - grunt lodash
env:
  matrix:
    - TEST=unit-mac-chrome
    - TEST=unit-mac-firefox
    - TEST=unit-mac-safari
    - TEST=unit-windows-firefox
    - TEST=unit-windows-chrome
    - TEST=unit-windows-ie-11
    - TEST=unit-windows-ie-10
    - TEST=unit-windows-ie-9
    - TEST=unit-linux-chrome
    - TEST=unit-linux-firefox
    - TEST=unit-ipad
    - TEST=unit-iphone
    - TEST=unit-android
  global:
    - secure: Kdqvk25nI86pIsTDA2G3eJxT0lYjYUifJeeXw+hUF1mnMC7yMcRLBVOLiDyUZvAgvezWrWaHRZ4JtgrIB118335z5WI9muT3Y8VB0HMsIYBYCjfFWKM334r/KaYVBkw+cspDPK7F9wNG26H7OCcIIs9FiHceI+qn2jdcAKLtAYk=
    - secure: ZmghdABEJqiqapOByzyvNxSyYh0dqZGxdtYD39q99w4buEMU/q9RP+kx5l91cIFm1Qy+H6Z6xkT1BMv35yo3wsHZX1IvGxeJeRmn4o4k487GBp8AZHsUUS8mLcwRItCNwMvjd3y9zqhm350qIuE+d2kTi1Knp6IEQOZytPk5+tY=
